languageCode = "en"
languageName = "English"
weight = 2
title = "Juan OG | Science"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Web personal docente"
dateFormat = "2 January 2006"
logo = "logo.png"

  [params.author]
#  name = "Juan OG"
#  image = "logo.png"
  headline = "By teaching, we learn."
  bio = "Teaching to think and a bit of Physics and Chemistry on the side."

