colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
firebase = { }
fathomAnalytics = { }
verification = { }

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = false
showRecentItems = "1"
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = "homepage_ini.jpeg"

[article]
showDate = false
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
sharingLinks = [
  "linkedin",
  "twitter",
  "whatsapp",
  "pinterest",
  "reddit",
  "facebook",
  "email"
]

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true
